"""add docs

Revision ID: 1a682359f52c
Revises: h0i1j2k3l4m5
Create Date: 2026-04-07 08:45:06.437590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a682359f52c'
down_revision: Union[str, None] = 'h0i1j2k3l4m5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_help_documents_updated_at'), table_name='help_documents')
    op.drop_index(op.f('ix_messages_category_created_at'), table_name='messages')
    op.drop_index(op.f('ix_user_messages_user_deleted_created'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_user_id_created_at'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_user_id_is_read'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_message_id'), 'user_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_user_messages_user_id'), 'user_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_user_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_message_id'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_user_id_is_read'), 'user_messages', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_user_messages_user_id_created_at'), 'user_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_messages_user_deleted_created'), 'user_messages', ['user_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_category_created_at'), 'messages', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_help_documents_updated_at'), 'help_documents', ['updated_at'], unique=False)
    # ### end Alembic commands ###
