"""圈地二期

Revision ID: 6c7e07520f6e
Revises: d4e5f6a7b8c9
Create Date: 2026-04-11 23:04:11.990593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7e07520f6e'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agri_drawn_parcel_region_id'), table_name='agri_drawn_parcel')
    op.drop_index(op.f('ix_agri_drawn_parcel_user_id'), table_name='agri_drawn_parcel')
    op.drop_index(op.f('ix_agri_drawn_obs_parcel_index_date'), table_name='agri_drawn_parcel_index_observation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agri_drawn_obs_parcel_index_date'), 'agri_drawn_parcel_index_observation', ['drawn_parcel_id', 'index_key', 'obs_date'], unique=False)
    op.create_index(op.f('ix_agri_drawn_parcel_user_id'), 'agri_drawn_parcel', ['user_id'], unique=False)
    op.create_index(op.f('ix_agri_drawn_parcel_region_id'), 'agri_drawn_parcel', ['region_id'], unique=False)
    # ### end Alembic commands ###
