"""add  argi

Revision ID: bf8026755c7d
Revises: k3l4m5n6o7p8
Create Date: 2026-04-10 09:07:58.191594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8026755c7d'
down_revision: Union[str, None] = 'k3l4m5n6o7p8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agri_parcel_region_id'), table_name='agri_parcel')
    op.drop_index(op.f('ix_agri_obs_parcel_index_date'), table_name='agri_parcel_index_observation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agri_obs_parcel_index_date'), 'agri_parcel_index_observation', ['parcel_id', 'index_key', 'obs_date'], unique=False)
    op.create_index(op.f('ix_agri_parcel_region_id'), 'agri_parcel', ['region_id'], unique=False)
    # ### end Alembic commands ###
